# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a91b55992cbbdde90ee32b88f445ea8e52dc077f207d311d7d89814d28e9591e4e9df6d23145fceeac21b9635f794ce575662b61487771dfebd0e44dd591ba05

test:
  secret_key_base: 3344b24580491e669c9bb6a8b70c5863fcd7a45abe01765b930d40a8473fc4179299dd1049b76b5f0b1532cc2bde84411ed8a258ddbd250146ba872dd454276f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
